targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/data/api/model/responses/{{}}.dart': 'lib/data/api/model/responses/generated/{{}}.g.dart'