name: app_template
description: Template mobile app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # стейт менеджмент
  flutter_bloc: 8.1.0
  bloc_concurrency: 0.2.0
  freezed_annotation: 2.1.0

  # сеть
  dio: 4.0.6
  json_annotation: 4.6.0

  # локализация
  easy_localization: 3.0.2-dev

  # хранение локальных данных
  shared_preferences: 2.0.15
  flutter_secure_storage: 5.1.0

  # форматированные поля ввода
  mask_text_input_formatter: 2.4.0

  # автоматическое добавление зависимостей
  dep_gen: ^1.0.5

  # нативный сплеш
  flutter_native_splash: 2.2.9

  cupertino_icons: 1.0.5
  flutter_svg: 1.1.3
  carousel_slider: 4.1.1
  shimmer: 2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.10.0

  # кодогенерация
  build_runner: 2.2.0
  json_serializable: 6.3.1
  freezed: 2.1.0+1

  # локализация
  easy_localization_loader: 1.0.0

  # тестирование
  mockito: 5.3.0

dependency_overrides:
  # Because easy_localization_loader >=1.0.0 depends on xml ^5.0.2 and flutter_svg >=1.1.0 depends on xml ^6.0.1, easy_localization_loader >=1.0.0 is incompatible with flutter_svg >=1.1.0.
  xml: 5.0.2


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/languages/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_black.ttf
          weight: 900
        - asset: assets/fonts/inter_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/inter_bold.ttf
          weight: 700
        - asset: assets/fonts/inter_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_regular.ttf
          weight: 400
        - asset: assets/fonts/inter_light.ttf
          weight: 300
        - asset: assets/fonts/inter_extra_light.ttf
          weight: 200
        - asset: assets/fonts/inter_thin.ttf
          weight: 100
